{
 "title": "Rezolus/Scheduler",
 "tags": [
  "rezolus",
  "ebpf",
  "scheduler"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "label": "Data source", "query": "prometheus" },
   {
    "name": "instance",
    "label": "Instance",
    "query": {
     "query": "label_values(cpu_cores,instance)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Scheduler Performance", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Runqueue Latency P99",
   "type": "stat",
   "gridPos": { "h": 4, "w": 8, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "scheduler_runqueue_latency{instance=\"$instance\", percentile=\"99\"} / 1000000",
     "legendFormat": "P99 Latency (ms)"
    }
   ]
  },
  {
   "title": "Involuntary Context Switches/sec",
   "type": "stat",
   "gridPos": { "h": 4, "w": 8, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(scheduler_context_switch{instance=\"$instance\", kind=\"involuntary\"}[$__rate_interval]))",
     "legendFormat": "Ctx Switches/sec"
    }
   ]
  },
  {
   "title": "Average Running Time",
   "type": "stat",
   "gridPos": { "h": 4, "w": 8, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "scheduler_running{instance=\"$instance\", percentile=\"50\"} / 1000000",
     "legendFormat": "P50 Runtime (ms)"
    }
   ]
  },
  {
   "title": "Scheduler Runqueue Latency Distribution",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "scheduler_runqueue_latency{instance=\"$instance\", percentile=\"50\"} / 1000000",
     "legendFormat": "p50"
    },
    {
     "expr": "scheduler_runqueue_latency{instance=\"$instance\", percentile=\"90\"} / 1000000",
     "legendFormat": "p90"
    },
    {
     "expr": "scheduler_runqueue_latency{instance=\"$instance\", percentile=\"99\"} / 1000000",
     "legendFormat": "p99"
    },
    {
     "expr": "scheduler_runqueue_latency{instance=\"$instance\", percentile=\"99.9\"} / 1000000",
     "legendFormat": "p99.9"
    }
   ]
  },
  {
   "title": "On-CPU Time Distribution",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "scheduler_running{instance=\"$instance\", percentile=\"50\"} / 1000000",
     "legendFormat": "p50"
    },
    {
     "expr": "scheduler_running{instance=\"$instance\", percentile=\"90\"} / 1000000",
     "legendFormat": "p90"
    },
    {
     "expr": "scheduler_running{instance=\"$instance\", percentile=\"99\"} / 1000000",
     "legendFormat": "p99"
    },
    {
     "expr": "scheduler_running{instance=\"$instance\", percentile=\"99.9\"} / 1000000",
     "legendFormat": "p99.9"
    }
   ]
  },
  {
   "title": "Off-CPU Time Distribution",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "scheduler_offcpu{instance=\"$instance\", percentile=\"50\"} / 1000000",
     "legendFormat": "p50"
    },
    {
     "expr": "scheduler_offcpu{instance=\"$instance\", percentile=\"90\"} / 1000000",
     "legendFormat": "p90"
    },
    {
     "expr": "scheduler_offcpu{instance=\"$instance\", percentile=\"99\"} / 1000000",
     "legendFormat": "p99"
    },
    {
     "expr": "scheduler_offcpu{instance=\"$instance\", percentile=\"99.9\"} / 1000000",
     "legendFormat": "p99.9"
    }
   ]
  },
  {
   "title": "Context Switch Rate",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 13 },
   "targets": [
    {
     "expr": "sum(rate(scheduler_context_switch{kind=\"involuntary\",instance=\"$instance\"}[$__rate_interval])) by (id)",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}