{
 "title": "Rezolus/Syscall",
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "label": "Data source", "query": "prometheus" },
   {
    "name": "instance",
    "label": "Instance",
    "query": {
     "query": "label_values(cpu_cores,instance)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "System Call Categories Breakdown",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum by (op) (rate(syscall{instance=\"$instance\"}[$__rate_interval]))",
     "legendFormat": "{{op}}"
    }
   ]
  },
  { "title": "System Call Analysis", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "Total",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(rate(syscall{instance=\"$instance\"}[$__rate_interval]))",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "Total Latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "sum(rate(syscall_latency{instance=\"$instance\"}[$__rate_interval])) by (percentile) / 1000000",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Read",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(rate(syscall{op=\"read\",instance=\"$instance\"}[$__rate_interval]))",
     "legendFormat": "Read - {{instance}}"
    }
   ]
  },
  {
   "title": "Read Latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "sum(rate(syscall_latency{instance=\"$instance\", op=\"read\"}[$__rate_interval])) by (percentile) / 1000000",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Write",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(rate(syscall{op=\"write\",instance=\"$instance\"}[$__rate_interval]))",
     "legendFormat": "Read - {{instance}}"
    }
   ]
  },
  {
   "title": "Write Latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "sum(rate(syscall_latency{instance=\"$instance\", op=\"write\"}[$__rate_interval])) by (percentile) / 1000000",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Poll",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(rate(syscall{op=\"poll\",instance=\"$instance\"}[$__rate_interval]))",
     "legendFormat": "Read - {{instance}}"
    }
   ]
  },
  {
   "title": "Poll Latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "sum(rate(syscall_latency{instance=\"$instance\", op=\"poll\"}[$__rate_interval])) by (percentile) / 1000000",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Socket",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 42 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(rate(syscall{op=\"socket\",instance=\"$instance\"}[$__rate_interval]))",
     "legendFormat": "Read - {{instance}}"
    }
   ]
  },
  {
   "title": "Socket Latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 42 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "sum(rate(syscall_latency{instance=\"$instance\", op=\"socket\"}[$__rate_interval])) by (percentile) / 1000000",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Lock",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 50 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(rate(syscall{op=\"lock\",instance=\"$instance\"}[$__rate_interval]))",
     "legendFormat": "Read - {{instance}}"
    }
   ]
  },
  {
   "title": "Lock Latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 50 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "sum(rate(syscall_latency{instance=\"$instance\", op=\"lock\"}[$__rate_interval])) by (percentile) / 1000000",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 58 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(rate(syscall{op=\"time\",instance=\"$instance\"}[$__rate_interval]))",
     "legendFormat": "Read - {{instance}}"
    }
   ]
  },
  {
   "title": "Time Latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 58 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "sum(rate(syscall_latency{instance=\"$instance\", op=\"time\"}[$__rate_interval])) by (percentile) / 1000000",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Sleep",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 66 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(rate(syscall{op=\"sleep\",instance=\"$instance\"}[$__rate_interval]))",
     "legendFormat": "Read - {{instance}}"
    }
   ]
  },
  {
   "title": "Sleep Latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 66 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "sum(rate(syscall_latency{instance=\"$instance\", op=\"sleep\"}[$__rate_interval])) by (percentile) / 1000000",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Yield",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 74 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(rate(syscall{op=\"yield\",instance=\"$instance\"}[$__rate_interval]))",
     "legendFormat": "Read - {{instance}}"
    }
   ]
  },
  {
   "title": "Yield Latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 74 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "sum(rate(syscall_latency{instance=\"$instance\", op=\"yield\"}[$__rate_interval])) by (percentile) / 1000000",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Filesystem",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 82 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(rate(syscall{op=\"filesystem\",instance=\"$instance\"}[$__rate_interval]))",
     "legendFormat": "Read - {{instance}}"
    }
   ]
  },
  {
   "title": "Filesystem Latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 82 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "sum(rate(syscall_latency{instance=\"$instance\", op=\"filesystem\"}[$__rate_interval])) by (percentile) / 1000000",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 90 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(rate(syscall{op=\"memory\",instance=\"$instance\"}[$__rate_interval]))",
     "legendFormat": "Read - {{instance}}"
    }
   ]
  },
  {
   "title": "Memory Latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 90 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "sum(rate(syscall_latency{instance=\"$instance\", op=\"memory\"}[$__rate_interval])) by (percentile) / 1000000",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Process",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 98 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(rate(syscall{op=\"process\",instance=\"$instance\"}[$__rate_interval]))",
     "legendFormat": "Read - {{instance}}"
    }
   ]
  },
  {
   "title": "Process Latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 98 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "sum(rate(syscall_latency{instance=\"$instance\", op=\"process\"}[$__rate_interval])) by (percentile) / 1000000",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Query",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 106 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(rate(syscall{op=\"query\",instance=\"$instance\"}[$__rate_interval]))",
     "legendFormat": "Read - {{instance}}"
    }
   ]
  },
  {
   "title": "Query Latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 106 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "sum(rate(syscall_latency{instance=\"$instance\", op=\"query\"}[$__rate_interval])) by (percentile) / 1000000",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "IPC",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 114 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(rate(syscall{op=\"ipc\",instance=\"$instance\"}[$__rate_interval]))",
     "legendFormat": "Read - {{instance}}"
    }
   ]
  },
  {
   "title": "IPC Latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 114 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "sum(rate(syscall_latency{instance=\"$instance\", op=\"ipc\"}[$__rate_interval])) by (percentile) / 1000000",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Timer",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 122 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(rate(syscall{op=\"timer\",instance=\"$instance\"}[$__rate_interval]))",
     "legendFormat": "Read - {{instance}}"
    }
   ]
  },
  {
   "title": "Timer Latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 122 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "sum(rate(syscall_latency{instance=\"$instance\", op=\"timer\"}[$__rate_interval])) by (percentile) / 1000000",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Event",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 130 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(rate(syscall{op=\"event\",instance=\"$instance\"}[$__rate_interval]))",
     "legendFormat": "Read - {{instance}}"
    }
   ]
  },
  {
   "title": "Event Latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 130 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "sum(rate(syscall_latency{instance=\"$instance\", op=\"event\"}[$__rate_interval])) by (percentile) / 1000000",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Other",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 138 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(rate(syscall{op=\"other\",instance=\"$instance\"}[$__rate_interval]))",
     "legendFormat": "Read - {{instance}}"
    }
   ]
  },
  {
   "title": "Other Latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 138 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "sum(rate(syscall_latency{instance=\"$instance\", op=\"other\"}[$__rate_interval])) by (percentile) / 1000000",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}