{
 "title": "Rezolus/CPU",
 "tags": [
  "rezolus",
  "ebpf",
  "cpu",
  "memory"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "label": "Data source", "query": "prometheus" },
   {
    "name": "instance",
    "label": "Instance",
    "query": {
     "query": "label_values(cpu_cores,instance)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Utilization", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Busy %",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "(sum(rate(cpu_usage{instance=\"$instance\"}[$__rate_interval])) / sum(cpu_cores{instance=\"$instance\"})) / 1000000000.0",
     "legendFormat": "{{id}}"
    }
   ]
  },
  {
   "title": "Busy %",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "targets": [
    {
     "expr": "sum(rate(cpu_usage{instance=\"$instance\", state=~\"system|user\"}[$__rate_interval])) by (id) / 1000000000.0",
     "legendFormat": "{{id}}"
    }
   ]
  },
  {
   "title": "System %",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum(rate(cpu_usage{instance=\"$instance\", state=\"system\"}[$__rate_interval])) / sum(cpu_cores{instance=\"$instance\"}) / 1000000000.0",
     "legendFormat": "{{id}}"
    }
   ]
  },
  {
   "title": "System %",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "targets": [
    {
     "expr": "sum by (id) (rate(cpu_usage{instance=\"$instance\", state=\"system\"}[1m])) / 1000000000.0",
     "legendFormat": "{{id}}"
    }
   ]
  },
  {
   "title": "User %",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum(rate(cpu_usage{instance=\"$instance\", state=\"user\"}[$__rate_interval])) / sum(cpu_cores{instance=\"$instance\"}) / 1000000000.0",
     "legendFormat": "user"
    }
   ]
  },
  {
   "title": "CPU Usage(user)% Heatmap by Core",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
   "targets": [
    {
     "expr": "sum by (id) (rate(cpu_usage{instance=\"$instance\", state=\"user\"}[1m])) / 1000000000.0",
     "legendFormat": "{{id}}"
    }
   ]
  },
  { "title": "CPU Performance", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 25 } },
  {
   "title": "Instructions Per Cycle (IPC)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 26 },
   "targets": [
    {
     "expr": "sum(rate(cpu_instructions{instance=\"$instance\"}[$__rate_interval])) / sum(rate(cpu_cycles{instance=\"$instance\"}[$__rate_interval]))",
     "legendFormat": "IPC"
    }
   ]
  },
  {
   "title": "Instructions Per Cycle (IPC) by Core",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 26 },
   "targets": [
    {
     "expr": "sum(rate(cpu_instructions{instance=\"$instance\"}[$__rate_interval])) by (id) / sum(rate(cpu_cycles{instance=\"$instance\"}[$__rate_interval])) by (id)",
     "legendFormat": "{{id}}"
    }
   ]
  },
  {
   "title": "Instructions per Nanosecond(IPNS)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 34 },
   "targets": [
    {
     "expr": "sum(rate(cpu_instructions{instance=\"$instance\"}[$__rate_interval])) / sum(rate(cpu_cycles{instance=\"$instance\"}[$__rate_interval])) * sum(rate(cpu_tsc{instance=\"$instance\"}[$__rate_interval])) * sum(rate(cpu_aperf{instance=\"$instance\"}[$__rate_interval])) / sum(rate(cpu_mperf{instance=\"$instance\"}[$__rate_interval])) / 1000000000.0 / sum(cpu_cores{instance=\"$instance\"})",
     "legendFormat": "Avg IPNS"
    }
   ]
  },
  {
   "title": "Instructions per Nanosecond per Core",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 34 },
   "targets": [
    {
     "expr": "sum(rate(cpu_instructions{instance=\"$instance\"}[$__rate_interval])) by (id) / sum(rate(cpu_cycles{instance=\"$instance\"}[$__rate_interval])) by (id) * sum(rate(cpu_tsc{instance=\"$instance\"}[$__rate_interval])) by (id) * sum(rate(cpu_aperf{instance=\"$instance\"}[$__rate_interval])) by (id) / sum(rate(cpu_mperf{instance=\"$instance\"}[$__rate_interval])) by (id) / 1000000000.0",
     "legendFormat": "{{id}}"
    }
   ]
  },
  {
   "title": "Frequency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 42 },
   "fieldConfig": { "defaults": { "unit": "rothz" } },
   "targets": [
    {
     "expr": "sum(rate(cpu_tsc{instance=\"$instance\"}[$__rate_interval])) * sum(rate(cpu_aperf{instance=\"$instance\"}[$__rate_interval])) / sum(rate(cpu_mperf{instance=\"$instance\"}[$__rate_interval])) / sum(cpu_cores{instance=\"$instance\"})",
     "legendFormat": "Avg IPNS"
    }
   ]
  },
  {
   "title": "Frequency by Core",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 42 },
   "targets": [
    {
     "expr": "sum(rate(cpu_tsc{instance=\"$instance\"}[$__rate_interval])) by (id) * sum(rate(cpu_aperf{instance=\"$instance\"}[$__rate_interval])) by (id) / sum(rate(cpu_mperf{instance=\"$instance\"}[$__rate_interval])) by (id)",
     "legendFormat": "{{id}}"
    }
   ]
  },
  {
   "title": "L3 Cache Performance",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 50 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum(rate(cpu_l3_miss{instance=\"$instance\"}[$__rate_interval])) / sum(rate(cpu_l3_access{instance=\"$instance\"}[$__rate_interval]))",
     "legendFormat": "L3 Miss %"
    }
   ]
  },
  {
   "title": "L3 Cache Performance by Core",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 50 },
   "targets": [
    {
     "expr": "sum(rate(cpu_l3_miss{instance=\"$instance\"}[$__rate_interval])) by (id) / sum(rate(cpu_l3_access{instance=\"$instance\"}[$__rate_interval])) by (id)",
     "legendFormat": "{{id}}"
    }
   ]
  },
  { "title": "Migrations", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 58 } },
  {
   "title": "To",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 59 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(rate(cpu_migrations{instance=\"$instance\", direction=\"to\"}[$__rate_interval]))",
     "legendFormat": "{{id}}-{{direction}}"
    }
   ]
  },
  {
   "title": "To",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 59 },
   "targets": [
    {
     "expr": "sum(rate(cpu_migrations{instance=\"$instance\", direction=\"to\"}[$__rate_interval])) by (id)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "From",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 67 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(rate(cpu_migrations{instance=\"$instance\", direction=\"from\"}[$__rate_interval]))",
     "legendFormat": "{{id}}-{{direction}}"
    }
   ]
  },
  {
   "title": "From",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 67 },
   "targets": [
    {
     "expr": "sum(rate(cpu_migrations{instance=\"$instance\", direction=\"from\"}[$__rate_interval])) by (id)",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "TLB Flush", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 75 } },
  {
   "title": "Total",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 76 },
   "fieldConfig": { "defaults": { "unit": "eps" } },
   "targets": [
    {
     "expr": "sum(rate(cpu_tlb_flush{instance=\"$instance\"}[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 76 },
   "targets": [
    {
     "expr": "sum(rate(cpu_tlb_flush{instance=\"$instance\"}[$__rate_interval])) by (id)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Local MM Shootdown",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 84 },
   "fieldConfig": { "defaults": { "unit": "eps" } },
   "targets": [
    {
     "expr": "sum(rate(cpu_tlb_flush{instance=\"$instance\", reason=\"local_mm_shootdown\"}[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Local MM Shootdown",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 84 },
   "targets": [
    {
     "expr": "sum(rate(cpu_tlb_flush{instance=\"$instance\", reason=\"local_mm_shootdown\"}[$__rate_interval])) by (id)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Remote Shootdown",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 92 },
   "fieldConfig": { "defaults": { "unit": "eps" } },
   "targets": [
    {
     "expr": "sum(rate(cpu_tlb_flush{instance=\"$instance\", reason=\"remote_shootdown\"}[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Remote Shootdown",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 92 },
   "targets": [
    {
     "expr": "sum(rate(cpu_tlb_flush{instance=\"$instance\", reason=\"remote_shootdown\"}[$__rate_interval])) by (id)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Remote Send IPI",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 100 },
   "fieldConfig": { "defaults": { "unit": "eps" } },
   "targets": [
    {
     "expr": "sum(rate(cpu_tlb_flush{instance=\"$instance\", reason=\"remote_send_ipi\"}[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Remote Send IPI",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 100 },
   "targets": [
    {
     "expr": "sum(rate(cpu_tlb_flush{instance=\"$instance\", reason=\"remote_send_ipi\"}[$__rate_interval])) by (id)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Task Switch",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 108 },
   "fieldConfig": { "defaults": { "unit": "eps" } },
   "targets": [
    {
     "expr": "sum(rate(cpu_tlb_flush{instance=\"$instance\", reason=\"task_switch\"}[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Task Switch",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 108 },
   "targets": [
    {
     "expr": "sum(rate(cpu_tlb_flush{instance=\"$instance\", reason=\"task_switch\"}[$__rate_interval])) by (id)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "SoftIRQ",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 116 },
   "collapsed": true
  },
  {
   "title": "SoftIRQ Processing by Kind",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 117 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(rate(softirq{kind=\"net_rx\", instance=\"$instance\"}[$__rate_interval]))",
     "legendFormat": "NET RX"
    },
    {
     "expr": "sum(rate(softirq{kind=\"net_tx\", instance=\"$instance\"}[$__rate_interval]))",
     "legendFormat": "NET TX"
    },
    {
     "expr": "sum(rate(softirq{kind=\"timer\", instance=\"$instance\"}[$__rate_interval]))",
     "legendFormat": "Timer"
    },
    {
     "expr": "sum(rate(softirq{kind=\"sched\", instance=\"$instance\"}[$__rate_interval]))",
     "legendFormat": "Scheduler"
    },
    {
     "expr": "sum(rate(softirq{kind=\"rcu\", instance=\"$instance\"}[$__rate_interval]))",
     "legendFormat": "RCU"
    },
    {
     "expr": "sum(rate(softirq{kind=\"block\", instance=\"$instance\"}[$__rate_interval]))",
     "legendFormat": "Block"
    }
   ]
  },
  {
   "title": "SoftIRQ Processing by Core",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 117 },
   "targets": [
    {
     "expr": "sum(rate(softirq{instance=\"$instance\"}[$__rate_interval])) by (id)",
     "legendFormat": "{{id}}"
    }
   ]
  },
  {
   "title": "SoftIRQ Processing Time by Kind",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 125 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    {
     "expr": "sum(rate(softirq_time{kind=\"net_rx\", instance=\"$instance\"}[$__rate_interval]))",
     "legendFormat": "NET RX Time"
    },
    {
     "expr": "sum(rate(softirq_time{kind=\"net_tx\", instance=\"$instance\"}[$__rate_interval]))",
     "legendFormat": "NET TX Time"
    },
    {
     "expr": "sum(rate(softirq_time{kind=\"timer\", instance=\"$instance\"}[$__rate_interval]))",
     "legendFormat": "Timer Time"
    },
    {
     "expr": "sum(rate(softirq_time{kind=\"sched\", instance=\"$instance\"}[$__rate_interval]))",
     "legendFormat": "Scheduler Time"
    }
   ]
  },
  {
   "title": "SoftIRQ Processing Time by Core",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 125 },
   "targets": [
    {
     "expr": "sum(rate(softirq_time{instance=\"$instance\"}[$__rate_interval])) by (id)",
     "legendFormat": "{{id}}"
    }
   ]
  }
 ]
}