{
 "title": "Rezolus/SoftIRQ",
 "tags": [
  "rezolus",
  "ebpf",
  "cpu",
  "memory"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "label": "Data source", "query": "prometheus" },
   {
    "name": "instance",
    "label": "Instance",
    "query": {
     "query": "label_values(cpu_cores,instance)"
    }
   }
  ]
 },
 "panels": [
  { "title": "SoftIRQ", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "eps" } },
   "targets": [
    {
     "expr": "sum(rate(softirq{instance=\"$instance\"}[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Rate by Core",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "targets": [
    {
     "expr": "sum(rate(softirq{instance=\"$instance\"}[$__rate_interval])) by (id)",
     "legendFormat": "{{id}}"
    }
   ]
  },
  {
   "title": "CPU %",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum(rate(softirq_time{instance=\"$instance\"}[$__rate_interval])) / sum(cpu_cores{instance=\"$instance\"}) / 1000000000.0",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU %",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "targets": [
    {
     "expr": "sum(rate(softirq_time{instance=\"$instance\"}[$__rate_interval])) by (id) / 1000000000.0",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Hardware Interrupts", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 } },
  {
   "title": "Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "eps" } },
   "targets": [
    {
     "expr": "sum(rate(softirq{instance=\"$instance\", kind=\"hi\"}[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Rate by Core",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 18 },
   "targets": [
    {
     "expr": "sum(rate(softirq{instance=\"$instance\", kind=\"hi\"}[$__rate_interval])) by (id)",
     "legendFormat": "{{id}}"
    }
   ]
  },
  {
   "title": "CPU %",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum(rate(softirq_time{instance=\"$instance\", kind=\"hi\"}[$__rate_interval])) / sum(cpu_cores{instance=\"$instance\"}) / 1000000000.0",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU %",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 26 },
   "targets": [
    {
     "expr": "sum(rate(softirq_time{instance=\"$instance\", kind=\"hi\"}[$__rate_interval])) by (id) / 1000000000.0",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Network Transmit", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 34 } },
  {
   "title": "Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "eps" } },
   "targets": [
    {
     "expr": "sum(rate(softirq{instance=\"$instance\", kind=\"net_tx\"}[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Rate by Core",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 35 },
   "targets": [
    {
     "expr": "sum(rate(softirq{instance=\"$instance\", kind=\"net_tx\"}[$__rate_interval])) by (id)",
     "legendFormat": "{{id}}"
    }
   ]
  },
  {
   "title": "CPU %",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 43 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum(rate(softirq_time{instance=\"$instance\", kind=\"net_tx\"}[$__rate_interval])) / sum(cpu_cores{instance=\"$instance\"}) / 1000000000.0",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU %",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 43 },
   "targets": [
    {
     "expr": "sum(rate(softirq_time{instance=\"$instance\", kind=\"net_tx\"}[$__rate_interval])) by (id) / 1000000000.0",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Network Receive", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 51 } },
  {
   "title": "Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 52 },
   "fieldConfig": { "defaults": { "unit": "eps" } },
   "targets": [
    {
     "expr": "sum(rate(softirq{instance=\"$instance\", kind=\"net_rx\"}[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Rate by Core",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 52 },
   "targets": [
    {
     "expr": "sum(rate(softirq{instance=\"$instance\", kind=\"net_rx\"}[$__rate_interval])) by (id)",
     "legendFormat": "{{id}}"
    }
   ]
  },
  {
   "title": "CPU %",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 60 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum(rate(softirq_time{instance=\"$instance\", kind=\"net_rx\"}[$__rate_interval])) / sum(cpu_cores{instance=\"$instance\"}) / 1000000000.0",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU %",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 60 },
   "targets": [
    {
     "expr": "sum(rate(softirq_time{instance=\"$instance\", kind=\"net_rx\"}[$__rate_interval])) by (id) / 1000000000.0",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Sched", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 68 } },
  {
   "title": "Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 69 },
   "fieldConfig": { "defaults": { "unit": "eps" } },
   "targets": [
    {
     "expr": "sum(rate(softirq{instance=\"$instance\", kind=\"sched\"}[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Rate by Core",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 69 },
   "targets": [
    {
     "expr": "sum(rate(softirq{instance=\"$instance\", kind=\"sched\"}[$__rate_interval])) by (id)",
     "legendFormat": "{{id}}"
    }
   ]
  },
  {
   "title": "CPU %",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 77 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum(rate(softirq_time{instance=\"$instance\", kind=\"sched\"}[$__rate_interval])) / sum(cpu_cores{instance=\"$instance\"}) / 1000000000.0",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU %",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 77 },
   "targets": [
    {
     "expr": "sum(rate(softirq_time{instance=\"$instance\", kind=\"sched\"}[$__rate_interval])) by (id) / 1000000000.0",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "RCU", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 85 } },
  {
   "title": "Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 86 },
   "fieldConfig": { "defaults": { "unit": "eps" } },
   "targets": [
    {
     "expr": "sum(rate(softirq{instance=\"$instance\", kind=\"rcu\"}[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Rate by Core",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 86 },
   "targets": [
    {
     "expr": "sum(rate(softirq{instance=\"$instance\", kind=\"rcu\"}[$__rate_interval])) by (id)",
     "legendFormat": "{{id}}"
    }
   ]
  },
  {
   "title": "CPU %",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 94 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum(rate(softirq_time{instance=\"$instance\", kind=\"rcu\"}[$__rate_interval])) / sum(cpu_cores{instance=\"$instance\"}) / 1000000000.0",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU %",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 94 },
   "targets": [
    {
     "expr": "sum(rate(softirq_time{instance=\"$instance\", kind=\"rcu\"}[$__rate_interval])) by (id) / 1000000000.0",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Tasklet", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 102 } },
  {
   "title": "Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 103 },
   "fieldConfig": { "defaults": { "unit": "eps" } },
   "targets": [
    {
     "expr": "sum(rate(softirq{instance=\"$instance\", kind=\"tasklet\"}[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Rate by Core",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 103 },
   "targets": [
    {
     "expr": "sum(rate(softirq{instance=\"$instance\", kind=\"tasklet\"}[$__rate_interval])) by (id)",
     "legendFormat": "{{id}}"
    }
   ]
  },
  {
   "title": "CPU %",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 111 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum(rate(softirq_time{instance=\"$instance\", kind=\"tasklet\"}[$__rate_interval])) / sum(cpu_cores{instance=\"$instance\"}) / 1000000000.0",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU %",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 111 },
   "targets": [
    {
     "expr": "sum(rate(softirq_time{instance=\"$instance\", kind=\"tasklet\"}[$__rate_interval])) by (id) / 1000000000.0",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Timer", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 119 } },
  {
   "title": "Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 120 },
   "fieldConfig": { "defaults": { "unit": "eps" } },
   "targets": [
    {
     "expr": "sum(rate(softirq{instance=\"$instance\", kind=\"timer\"}[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Rate by Core",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 120 },
   "targets": [
    {
     "expr": "sum(rate(softirq{instance=\"$instance\", kind=\"timer\"}[$__rate_interval])) by (id)",
     "legendFormat": "{{id}}"
    }
   ]
  },
  {
   "title": "CPU %",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 128 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum(rate(softirq_time{instance=\"$instance\", kind=\"timer\"}[$__rate_interval])) / sum(cpu_cores{instance=\"$instance\"}) / 1000000000.0",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU %",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 128 },
   "targets": [
    {
     "expr": "sum(rate(softirq_time{instance=\"$instance\", kind=\"timer\"}[$__rate_interval])) by (id) / 1000000000.0",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "HRTimer", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 136 } },
  {
   "title": "Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 137 },
   "fieldConfig": { "defaults": { "unit": "eps" } },
   "targets": [
    {
     "expr": "sum(rate(softirq{instance=\"$instance\", kind=\"hrtimer\"}[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Rate by Core",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 137 },
   "targets": [
    {
     "expr": "sum(rate(softirq{instance=\"$instance\", kind=\"hrtimer\"}[$__rate_interval])) by (id)",
     "legendFormat": "{{id}}"
    }
   ]
  },
  {
   "title": "CPU %",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 145 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum(rate(softirq_time{instance=\"$instance\", kind=\"hrtimer\"}[$__rate_interval])) / sum(cpu_cores{instance=\"$instance\"}) / 1000000000.0",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU %",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 145 },
   "targets": [
    {
     "expr": "sum(rate(softirq_time{instance=\"$instance\", kind=\"hrtimer\"}[$__rate_interval])) by (id) / 1000000000.0",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Block", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 153 } },
  {
   "title": "Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 154 },
   "fieldConfig": { "defaults": { "unit": "eps" } },
   "targets": [
    {
     "expr": "sum(rate(softirq{instance=\"$instance\", kind=\"block\"}[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Rate by Core",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 154 },
   "targets": [
    {
     "expr": "sum(rate(softirq{instance=\"$instance\", kind=\"block\"}[$__rate_interval])) by (id)",
     "legendFormat": "{{id}}"
    }
   ]
  },
  {
   "title": "CPU %",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 162 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum(rate(softirq_time{instance=\"$instance\", kind=\"block\"}[$__rate_interval])) / sum(cpu_cores{instance=\"$instance\"}) / 1000000000.0",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU %",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 162 },
   "targets": [
    {
     "expr": "sum(rate(softirq_time{instance=\"$instance\", kind=\"block\"}[$__rate_interval])) by (id) / 1000000000.0",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}