{
 "title": "Rezolus/Overview",
 "tags": [
  "rezolus",
  "ebpf"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "label": "Data source", "query": "prometheus" },
   {
    "name": "instance",
    "label": "Instance",
    "query": {
     "query": "label_values(cpu_cores,instance)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Utilization", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Busy %",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "(sum(rate(cpu_usage{instance=\"$instance\"}[5m])) / sum(cpu_cores{instance=\"$instance\"})) / 1000000000.0",
     "legendFormat": "{{id}}"
    }
   ]
  },
  {
   "title": "Busy %",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "targets": [
    {
     "expr": "sum(rate(cpu_usage{instance=\"$instance\", state=~\"system|user\"}[5m])) by (id) / 1000000000.0",
     "legendFormat": "{{id}}"
    }
   ]
  },
  { "title": "Network", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "Transmit Bandwidth",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "binbps" } },
   "targets": [
    {
     "expr": "sum(rate(network_bytes{instance=\"$instance\", direction=\"transmit\"}[$__rate_interval])) * 8",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Receive Bandwidth",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "binbps" } },
   "targets": [
    {
     "expr": "sum(rate(network_bytes{instance=\"$instance\", direction=\"receive\"}[$__rate_interval])) * 8",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Transmit Packets",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "targets": [
    {
     "expr": "sum(rate(network_packets{instance=\"$instance\", direction=\"transmit\"}[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Receive Packets",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "targets": [
    {
     "expr": "sum(rate(network_packets{instance=\"$instance\", direction=\"receive\"}[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "TCP Packet Latency",
   "type": "timeseries",
   "description": "Measures latency from a packet being received until application reads from the socket. This metric captures how quickly applications respond to incoming data, which can reveal application processing bottlenecks or inefficient socket read patterns. High latencies here often indicate that applications aren't reading from sockets promptly, which can lead to increased memory usage and network bottlenecks.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    {
     "expr": "sum(rate(tcp_packet_latency{instance=\"$instance\"}[$__rate_interval])) by (percentile)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "TCP Connect Latency",
   "type": "timeseries",
   "description": "Measures the latency for establishing TCP connections. High connect latencies may indicate network congestion, DNS resolution problems, or overloaded servers. These metrics are particularly valuable for monitoring client-side connection performance.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    {
     "expr": "sum(rate(tcp_connect_latency{instance=\"$instance\"}[$__rate_interval])) by (percentile)",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Scheduler", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 34 } },
  {
   "title": "Runqueue Latency",
   "type": "timeseries",
   "description": "Distribution of the amount of time tasks were waiting in the runqueue",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    {
     "expr": "sum(rate(scheduler_runqueue_latency{instance=\"$instance\"}[$__rate_interval])) by (percentile)",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Syscall", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 43 } },
  {
   "title": "Total",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 44 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(rate(syscall{instance=\"$instance\"}[$__rate_interval]))",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "Total",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 44 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    {
     "expr": "sum(rate(syscall_latency{instance=\"$instance\"}[$__rate_interval])) by (percentile)",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "SoftIRQ", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 52 } },
  {
   "title": "Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 53 },
   "targets": [
    {
     "expr": "sum(rate(softirq{instance=\"$instance\"}[$__rate_interval]))",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "Rate",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 53 },
   "targets": [
    {
     "expr": "sum(rate(softirq{instance=\"$instance\"}[$__rate_interval])) by (id)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU %",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 61 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum(rate(softirq_time{instance=\"$instance\"}[$__rate_interval])) / sum(cpu_cores{instance=\"$instance\"}) / 1000000000.0",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "CPU %",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 61 },
   "targets": [
    {
     "expr": "sum(rate(softirq_time{instance=\"$instance\"}[$__rate_interval])) by (id) / 1000000000.0",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "BlockIO", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 69 } },
  {
   "title": "Read Throughput",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 70 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(rate(blockio_bytes{instance=\"$instance\", op=\"read\"}[$__rate_interval]))",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "Write Throughput",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 70 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(rate(blockio_bytes{instance=\"$instance\", op=\"write\"}[$__rate_interval]))",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "Read IOPS",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 78 },
   "fieldConfig": { "defaults": { "unit": "iops" } },
   "targets": [
    {
     "expr": "sum(rate(blockio_operations{instance=\"$instance\", op=\"read\"}[$__rate_interval]))",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "Write IOPS",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 78 },
   "fieldConfig": { "defaults": { "unit": "iops" } },
   "targets": [
    {
     "expr": "sum(rate(blockio_operations{instance=\"$instance\", op=\"write\"}[$__rate_interval]))",
     "legendFormat": "Total"
    }
   ]
  }
 ]
}