fn main() {
    metric_descriptions::generate();

    #[cfg(target_os = "linux")]
    bpf::generate();
}

/// Extracts `name` and `description` from `#[metric(...)]` attributes in all
/// `stats.rs` files under `src/agent/samplers/`. Writes a static lookup table
/// to `$OUT_DIR/metric_descriptions.rs` so descriptions are available on every
/// platform regardless of which samplers are linked in.
mod metric_descriptions {
    use std::collections::BTreeMap;
    use std::io::Write;

    pub fn generate() {
        let out_dir = std::env::var("OUT_DIR").unwrap();
        let dest = std::path::Path::new(&out_dir).join("metric_descriptions.rs");

        let mut descriptions: BTreeMap<String, String> = BTreeMap::new();

        // Walk all stats.rs files under src/agent/samplers/
        for entry in glob("src/agent/samplers/**/stats.rs") {
            let content = std::fs::read_to_string(&entry).unwrap_or_default();
            parse_metric_attrs(&content, &mut descriptions);
            println!("cargo:rerun-if-changed={}", entry.display());
        }

        let mut out = std::fs::File::create(&dest).unwrap();
        writeln!(out, "/// Auto-generated by build.rs — do not edit.").unwrap();
        writeln!(
            out,
            "pub fn static_metric_descriptions() -> &'static [(&'static str, &'static str)] {{"
        )
        .unwrap();
        writeln!(out, "    &[").unwrap();
        for (name, desc) in &descriptions {
            // Escape any quotes in descriptions
            let escaped = desc.replace('\\', "\\\\").replace('"', "\\\"");
            writeln!(out, "        (\"{name}\", \"{escaped}\"),").unwrap();
        }
        writeln!(out, "    ]").unwrap();
        writeln!(out, "}}").unwrap();
    }

    /// Simple recursive glob for `**/stats.rs` patterns.
    fn glob(pattern: &str) -> Vec<std::path::PathBuf> {
        // pattern is like "src/agent/samplers/**/stats.rs"
        let parts: Vec<&str> = pattern.split("**/").collect();
        let base = std::path::Path::new(parts[0]);
        let filename = parts.get(1).unwrap_or(&"");
        let mut results = Vec::new();
        walk_dir(base, filename, &mut results);
        results.sort();
        results
    }

    fn walk_dir(dir: &std::path::Path, filename: &str, results: &mut Vec<std::path::PathBuf>) {
        let Ok(entries) = std::fs::read_dir(dir) else {
            return;
        };
        for entry in entries.flatten() {
            let path = entry.path();
            if path.is_dir() {
                walk_dir(&path, filename, results);
            } else if path.file_name().is_some_and(|n| n == filename) {
                results.push(path);
            }
        }
    }

    /// Parse `#[metric(name = "...", description = "...")]` from source text.
    fn parse_metric_attrs(src: &str, map: &mut BTreeMap<String, String>) {
        let mut i = 0;
        let bytes = src.as_bytes();
        while i < bytes.len() {
            // Find #[metric(
            if let Some(pos) = src[i..].find("#[metric(") {
                let start = i + pos;
                // Find the closing )]
                if let Some(end_offset) = src[start..].find(")]") {
                    let block = &src[start..start + end_offset + 2];
                    let name = extract_string_field(block, "name");
                    let desc = extract_string_field(block, "description");
                    if let (Some(name), Some(desc)) = (name, desc) {
                        // First description wins (metrics can share names with
                        // different label sets but the same description)
                        map.entry(name).or_insert(desc);
                    }
                    i = start + end_offset + 2;
                } else {
                    i = start + 9;
                }
            } else {
                break;
            }
        }
    }

    /// Extract a string value for a field like `name = "value"` from an
    /// attribute block.
    fn extract_string_field(block: &str, field: &str) -> Option<String> {
        let pattern = format!("{field} = \"");
        let start = block.find(&pattern)? + pattern.len();
        let rest = &block[start..];
        let end = rest.find('"')?;
        Some(rest[..end].to_string())
    }
}

#[cfg(target_os = "linux")]
mod bpf {
    use libbpf_cargo::SkeletonBuilder;

    // `SOURCES` lists all BPF programs and the sampler that contains them.
    // Each entry `(sampler, program)` maps to a unique path in the `samplers`
    // directory.
    const SOURCES: &[(&str, &str)] = &[
        ("blockio", "latency"),
        ("blockio", "requests"),
        ("cpu", "bandwidth"),
        ("cpu", "migrations"),
        ("cpu", "perf"),
        ("cpu", "tlb_flush"),
        ("cpu", "usage"),
        ("network", "interfaces"),
        ("network", "traffic"),
        ("scheduler", "runqueue"),
        ("syscall", "counts"),
        ("syscall", "latency"),
        ("tcp", "connect_latency"),
        ("tcp", "packet_latency"),
        ("tcp", "receive"),
        ("tcp", "retransmit"),
        ("tcp", "traffic"),
    ];

    pub fn generate() {
        let out_dir = std::env::var("OUT_DIR").unwrap();
        let target_arch = std::env::var("CARGO_CFG_TARGET_ARCH").unwrap();

        for (sampler, prog) in SOURCES {
            let src = format!("src/agent/samplers/{sampler}/linux/{prog}/mod.bpf.c");
            let tgt = format!("{out_dir}/{sampler}_{prog}.bpf.rs");

            if target_arch == "x86_64" {
                SkeletonBuilder::new()
                    .source(&src)
                    .clang_args([
                        "-Isrc/agent/bpf/x86_64",
                        "-fno-unwind-tables",
                        "-D__TARGET_ARCH_x86",
                        "-Wall",
                        "-Werror",
                    ])
                    .build_and_generate(&tgt)
                    .unwrap();
            } else if target_arch == "aarch64" {
                SkeletonBuilder::new()
                    .source(&src)
                    .clang_args([
                        "-Isrc/agent/bpf/aarch64",
                        "-fno-unwind-tables",
                        "-D__TARGET_ARCH_arm64",
                        "-Wall",
                        "-Werror",
                    ])
                    .build_and_generate(&tgt)
                    .unwrap();
            } else {
                panic!("BPF support only available for x86_64 and aarch64 architectures");
            }

            println!("cargo:rerun-if-changed={src}");
        }

        println!("cargo:rerun-if-changed=src/agent/bpf/histogram.h");
        println!("cargo:rerun-if-changed=src/agent/bpf/vmlinux.h");
    }
}
