{
 "title": "Rezolus",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "host", "query": { "query": "label_values(job)" } }
  ]
 },
 "panels": [
  { "title": "Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "CPU Busy %",
   "type": "timeseries",
   "description": "Total CPU utilization",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum by(job) (irate(cpu_usage{job=~\"$host\"}[$__rate_interval])) / on(job) cpu_cores / 1e9",
     "legendFormat": "{{job}} - correct"
    }
   ]
  },
  {
   "title": "CPU Busy %",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "targets": [
    {
     "expr": "sum by(id) (irate(cpu_usage{job=~\"$host\"}[$__rate_interval])) / 1e9",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Transmit Bandwidth",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "targets": [
    {
     "expr": "irate(network_bytes{job=~\"$host\",direction=\"transmit\"}[$__rate_interval]) * 8",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "Receive Bandwidth",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "targets": [
    {
     "expr": "irate(network_bytes{job=~\"$host\",direction=\"receive\"}[$__rate_interval]) * 8",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "Transmit Packets",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "targets": [
    {
     "expr": "irate(network_packets{job=~\"$host\",direction=\"transmit\"}[$__rate_interval])",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "Receive Packets",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "targets": [
    {
     "expr": "irate(network_packets{job=~\"$host\",direction=\"receive\"}[$__rate_interval])",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "TCP Packet Latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    {
     "expr": "tcp_packet_latency{job=~\"$host\"}",
     "legendFormat": " p{{percentile}}"
    }
   ]
  },
  {
   "title": "Runqueue Latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    {
     "expr": "scheduler_runqueue_latency{job=~\"$host\"}",
     "legendFormat": "p{{percentile}}"
    }
   ]
  },
  {
   "title": "Syscall Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 33 },
   "targets": [
    {
     "expr": "sum(irate(syscall{job=~\"$host\"}[$__rate_interval]))",
     "legendFormat": "syscall/s"
    }
   ]
  },
  {
   "title": "CPU",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 41 },
   "collapsed": true,
   "panels": [
    {
     "title": "Busy %",
     "type": "timeseries",
     "description": "Total CPU utilization",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 42 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "expr": "sum by(job) (irate(cpu_usage{job=~\"$host\"}[$__rate_interval])) / on(job) cpu_cores / 1e9",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Busy %",
     "type": "heatmap",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 42 },
     "targets": [
      {
       "expr": "sum by(id) (irate(cpu_usage{job=~\"$host\"}[$__rate_interval])) / 1e9",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "User %",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 290 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "expr": "sum by(job) (irate(cpu_usage{job=~\"$host\", state=\"user\"}[$__rate_interval])) / on(job) cpu_cores / 1e9",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "User %",
     "type": "heatmap",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 290 },
     "targets": [
      {
       "expr": "sum by(id) (irate(cpu_usage{job=~\"$host\", state=\"user\"}[$__rate_interval])) / 1e9",
       "legendFormat": "{{id}}"
      }
     ]
    },
    {
     "title": "System %",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 298 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "expr": "sum by(job) (irate(cpu_usage{job=~\"$host\", state=\"system\"}[$__rate_interval])) / on(job) cpu_cores / 1e9",
       "legendFormat": "{{job}}"
      }
     ]
    },
    {
     "title": "System %",
     "type": "heatmap",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 298 },
     "targets": [
      {
       "expr": "sum by(id) (irate(cpu_usage{job=~\"$host\", state=\"system\"}[$__rate_interval])) / 1e9",
       "legendFormat": "{{id}}"
      }
     ]
    },
    {
     "title": "IPC",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 306 },
     "targets": [
      {
       "expr": "sum(irate(cpu_instructions{job=~\"$host\"}[$__rate_interval])) / sum(irate(cpu_cycles[$__rate_interval]))",
       "legendFormat": "{{id}}"
      }
     ]
    },
    {
     "title": "IPC",
     "type": "heatmap",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 306 },
     "targets": [
      {
       "expr": "sum by(id) (irate(cpu_instructions{job=~\"$host\"}[$__rate_interval])) / sum by(id) (irate(cpu_cycles[$__rate_interval]))",
       "legendFormat": "{{id}}"
      }
     ]
    },
    {
     "title": "IPNS",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 314 },
     "targets": [
      {
       "expr": "sum by(job) (irate(cpu_instructions{job=\"$host\"}[$__rate_interval])) / sum by(job) ((irate(cpu_cycles[$__rate_interval]))) * sum by(job) (irate(cpu_tsc[$__rate_interval])) * sum by(job) (irate(cpu_aperf[5m])) / sum by(job) (irate(cpu_mperf[5m])) / on(job) cpu_cores / 1e9",
       "legendFormat": "{{id}}"
      }
     ]
    },
    {
     "title": "IPNS",
     "type": "heatmap",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 314 },
     "targets": [
      {
       "expr": "sum by(id) (irate(cpu_instructions{job=\"$host\"}[$__rate_interval])) / sum by(id) ((irate(cpu_cycles[$__rate_interval]))) * sum by(id) (irate(cpu_tsc[$__rate_interval])) * sum by(id) (irate(cpu_aperf[5m])) / sum by(id) (irate(cpu_mperf[5m])) / 1e9",
       "legendFormat": "{{id}}"
      }
     ]
    },
    {
     "title": "L3 Hit %",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 322 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "expr": "1 - (sum(irate(cpu_l3_miss{job=~\"$host\"}[$__rate_interval])) / sum(irate(cpu_l3_access[$__rate_interval])))",
       "legendFormat": "{{id}}"
      }
     ]
    },
    {
     "title": "L3 Hit %",
     "type": "heatmap",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 322 },
     "targets": [
      {
       "expr": "(1 - irate(cpu_l3_miss{job=~\"$host\"}[$__rate_interval])) / (irate(cpu_l3_access[$__rate_interval]))",
       "legendFormat": "{{id}}"
      }
     ]
    },
    {
     "title": "Frequency",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 330 },
     "fieldConfig": { "defaults": { "unit": "rothz" } },
     "targets": [
      {
       "expr": "sum by(job) (irate(cpu_tsc{job=\"$host\"}[$__rate_interval])) * sum by(job) (irate(cpu_aperf[5m])) / sum by(job) (irate(cpu_mperf[5m])) / on(job) cpu_cores",
       "legendFormat": "{{id}}"
      }
     ]
    },
    {
     "title": "Frequency",
     "type": "heatmap",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 330 },
     "targets": [
      {
       "expr": "sum by(id) (irate(cpu_tsc{job=\"$host\"}[$__rate_interval])) * sum by(id) (irate(cpu_aperf[5m])) / sum by(id) (irate(cpu_mperf[5m]))",
       "legendFormat": "{{id}}"
      }
     ]
    },
    {
     "title": "Migrations To",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 338 },
     "targets": [
      {
       "expr": "sum by(job) (irate(cpu_migrations{job=~\"$host\",direction=\"to\"}[$__rate_interval]))",
       "legendFormat": "{{job}}"
      }
     ]
    },
    {
     "title": "Migrations To",
     "type": "heatmap",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 338 },
     "targets": [
      {
       "expr": "sum by(id) (irate(cpu_migrations{job=~\"$host\", direction=\"to\"}[$__rate_interval]))",
       "legendFormat": "{{id}}"
      }
     ]
    },
    {
     "title": "Migrations From",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 346 },
     "targets": [
      {
       "expr": "sum by(job) (irate(cpu_migrations{job=~\"$host\",direction=\"from\"}[$__rate_interval]))",
       "legendFormat": "{{job}}"
      }
     ]
    },
    {
     "title": "Migrations From",
     "type": "heatmap",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 346 },
     "targets": [
      {
       "expr": "sum by(id) (irate(cpu_migrations{job=~\"$host\", direction=\"from\"}[$__rate_interval]))",
       "legendFormat": "{{id}}"
      }
     ]
    },
    {
     "title": "TLB Flush - Total",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 354 },
     "targets": [
      {
       "expr": "sum by(job) (irate(cpu_tlb_flush{job=~\"$host\"}[$__rate_interval]))",
       "legendFormat": "{{job}}"
      }
     ]
    },
    {
     "title": "TLB Flush - Total",
     "type": "heatmap",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 354 },
     "targets": [
      {
       "expr": "sum by(id) (irate(cpu_tlb_flush{job=~\"$host\"}[$__rate_interval]))",
       "legendFormat": "{{id}}"
      }
     ]
    },
    {
     "title": "TLB Flush",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 362 },
     "targets": [
      {
       "expr": "sum by(reason) (irate(cpu_tlb_flush{job=~\"$host\"}[$__rate_interval]))",
       "legendFormat": "{{job}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Network",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 42 },
   "collapsed": true,
   "panels": [
    {
     "title": "Transmit Packets",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 43 },
     "fieldConfig": { "defaults": { "unit": "pps" } },
     "targets": [
      {
       "expr": "irate(network_packets{job=~\"$host\",direction=\"transmit\"}[$__rate_interval])",
       "legendFormat": "{{job}}"
      }
     ]
    },
    {
     "title": "Receive Packets",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 43 },
     "fieldConfig": { "defaults": { "unit": "pps" } },
     "targets": [
      {
       "expr": "irate(network_packets{job=~\"$host\",direction=\"receive\"}[$__rate_interval])",
       "legendFormat": "{{job}}"
      }
     ]
    },
    {
     "title": "Transmit Bandwidth",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 51 },
     "fieldConfig": { "defaults": { "unit": "bps" } },
     "targets": [
      {
       "expr": "irate(network_bytes{job=~\"$host\",direction=\"transmit\"}[$__rate_interval]) * 8",
       "legendFormat": "{{job}}"
      }
     ]
    },
    {
     "title": "Receive Bandwidth",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 51 },
     "fieldConfig": { "defaults": { "unit": "bps" } },
     "targets": [
      {
       "expr": "irate(network_bytes{job=~\"$host\",direction=\"receive\"}[$__rate_interval]) * 8",
       "legendFormat": "{{job}}"
      }
     ]
    },
    {
     "title": "TCP Packet Latency",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 59 },
     "fieldConfig": { "defaults": { "unit": "ns" } },
     "targets": [
      {
       "expr": "tcp_packet_latency{job=~\"$host\"}",
       "legendFormat": " p{{percentile}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Scheduler",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 43 },
   "collapsed": true,
   "panels": [
    {
     "title": "Runqueue Latency",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 68 },
     "fieldConfig": { "defaults": { "unit": "ns" } },
     "targets": [
      {
       "expr": "scheduler_runqueue_latency{job=~\"$host\"}",
       "legendFormat": "p{{percentile}}"
      }
     ]
    },
    {
     "title": "Off CPU",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 68 },
     "fieldConfig": { "defaults": { "unit": "ns" } },
     "targets": [
      {
       "expr": "scheduler_offcpu{job=~\"$host\"}",
       "legendFormat": "p{{percentile}}"
      }
     ]
    },
    {
     "title": "Running",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 76 },
     "fieldConfig": { "defaults": { "unit": "ns" } },
     "targets": [
      {
       "expr": "scheduler_running{job=~\"$host\"}",
       "legendFormat": "p{{percentile}}"
      }
     ]
    },
    {
     "title": "Context Switches",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 76 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(irate(scheduler_context_switch{job=~\"$host\"}[$__rate_interval]))",
       "legendFormat": "{{job}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Syscall",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 44 },
   "collapsed": true,
   "panels": [
    {
     "title": "Read Rate",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 85 },
     "targets": [
      {
       "expr": "sum(irate(syscall{job=~\"$host\",op=\"read\"}[$__rate_interval]))",
       "legendFormat": "syscall/s"
      }
     ]
    },
    {
     "title": "Read Latency",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 85 },
     "fieldConfig": { "defaults": { "unit": "ns" } },
     "targets": [
      {
       "expr": "irate(syscall_latency{job=\"$host\",op=\"read\"}[$__rate_interval])",
       "legendFormat": "p{{percentile}}"
      }
     ]
    },
    {
     "title": "Write Rate",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 117 },
     "targets": [
      {
       "expr": "sum(irate(syscall{job=~\"$host\",op=\"write\"}[$__rate_interval]))",
       "legendFormat": "syscall/s"
      }
     ]
    },
    {
     "title": "Write Latency",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 117 },
     "fieldConfig": { "defaults": { "unit": "ns" } },
     "targets": [
      {
       "expr": "irate(syscall_latency{job=\"$host\",op=\"write\"}[$__rate_interval])",
       "legendFormat": "p{{percentile}}"
      }
     ]
    },
    {
     "title": "Poll Rate",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 125 },
     "targets": [
      {
       "expr": "sum(irate(syscall{job=~\"$host\",op=\"poll\"}[$__rate_interval]))",
       "legendFormat": "syscall/s"
      }
     ]
    },
    {
     "title": "Poll Latency",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 125 },
     "fieldConfig": { "defaults": { "unit": "ns" } },
     "targets": [
      {
       "expr": "irate(syscall_latency{job=\"$host\",op=\"poll\"}[$__rate_interval])",
       "legendFormat": "p{{percentile}}"
      }
     ]
    },
    {
     "title": "Socket Rate",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 173 },
     "targets": [
      {
       "expr": "sum(irate(syscall{job=~\"$host\",op=\"socket\"}[$__rate_interval]))",
       "legendFormat": "syscall/s"
      }
     ]
    },
    {
     "title": "Socket Latency",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 173 },
     "fieldConfig": { "defaults": { "unit": "ns" } },
     "targets": [
      {
       "expr": "irate(syscall_latency{job=\"$host\",op=\"socket\"}[$__rate_interval])",
       "legendFormat": "p{{percentile}}"
      }
     ]
    },
    {
     "title": "Lock Rate",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 181 },
     "targets": [
      {
       "expr": "sum(irate(syscall{job=~\"$host\",op=\"lock\"}[$__rate_interval]))",
       "legendFormat": "syscall/s"
      }
     ]
    },
    {
     "title": "Lock Latency",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 181 },
     "fieldConfig": { "defaults": { "unit": "ns" } },
     "targets": [
      {
       "expr": "irate(syscall_latency{job=\"$host\",op=\"lock\"}[$__rate_interval])",
       "legendFormat": "p{{percentile}}"
      }
     ]
    },
    {
     "title": "Time Rate",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 189 },
     "targets": [
      {
       "expr": "sum(irate(syscall{job=~\"$host\",op=\"time\"}[$__rate_interval]))",
       "legendFormat": "syscall/s"
      }
     ]
    },
    {
     "title": "Time Latency",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 189 },
     "fieldConfig": { "defaults": { "unit": "ns" } },
     "targets": [
      {
       "expr": "irate(syscall_latency{job=\"$host\",op=\"time\"}[$__rate_interval])",
       "legendFormat": "p{{percentile}}"
      }
     ]
    },
    {
     "title": "Sleep Rate",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 197 },
     "targets": [
      {
       "expr": "sum(irate(syscall{job=~\"$host\",op=\"sleep\"}[$__rate_interval]))",
       "legendFormat": "syscall/s"
      }
     ]
    },
    {
     "title": "Sleep Latency",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 197 },
     "fieldConfig": { "defaults": { "unit": "ns" } },
     "targets": [
      {
       "expr": "irate(syscall_latency{job=\"$host\",op=\"sleep\"}[$__rate_interval])",
       "legendFormat": "p{{percentile}}"
      }
     ]
    },
    {
     "title": "Yield Rate",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 205 },
     "targets": [
      {
       "expr": "sum(irate(syscall{job=~\"$host\",op=\"yield\"}[$__rate_interval]))",
       "legendFormat": "syscall/s"
      }
     ]
    },
    {
     "title": "Yield Latency",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 205 },
     "fieldConfig": { "defaults": { "unit": "ns" } },
     "targets": [
      {
       "expr": "irate(syscall_latency{job=\"$host\",op=\"yield\"}[$__rate_interval])",
       "legendFormat": "p{{percentile}}"
      }
     ]
    },
    {
     "title": "Filesystem Rate",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 213 },
     "targets": [
      {
       "expr": "sum(irate(syscall{job=~\"$host\",op=\"filesystem\"}[$__rate_interval]))",
       "legendFormat": "syscall/s"
      }
     ]
    },
    {
     "title": "Filesystem Latency",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 213 },
     "fieldConfig": { "defaults": { "unit": "ns" } },
     "targets": [
      {
       "expr": "irate(syscall_latency{job=\"$host\",op=\"filesystem\"}[$__rate_interval])",
       "legendFormat": "p{{percentile}}"
      }
     ]
    },
    {
     "title": "Memory Rate",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 221 },
     "targets": [
      {
       "expr": "sum(irate(syscall{job=~\"$host\",op=\"memory\"}[$__rate_interval]))",
       "legendFormat": "syscall/s"
      }
     ]
    },
    {
     "title": "Memory Latency",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 221 },
     "fieldConfig": { "defaults": { "unit": "ns" } },
     "targets": [
      {
       "expr": "irate(syscall_latency{job=\"$host\",op=\"memory\"}[$__rate_interval])",
       "legendFormat": "p{{percentile}}"
      }
     ]
    },
    {
     "title": "Process Rate",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 229 },
     "targets": [
      {
       "expr": "sum(irate(syscall{job=~\"$host\",op=\"process\"}[$__rate_interval]))",
       "legendFormat": "syscall/s"
      }
     ]
    },
    {
     "title": "Process Latency",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 229 },
     "fieldConfig": { "defaults": { "unit": "ns" } },
     "targets": [
      {
       "expr": "irate(syscall_latency{job=\"$host\",op=\"process\"}[$__rate_interval])",
       "legendFormat": "p{{percentile}}"
      }
     ]
    },
    {
     "title": "Query Rate",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 237 },
     "targets": [
      {
       "expr": "sum(irate(syscall{job=~\"$host\",op=\"query\"}[$__rate_interval]))",
       "legendFormat": "syscall/s"
      }
     ]
    },
    {
     "title": "Query Latency",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 237 },
     "fieldConfig": { "defaults": { "unit": "ns" } },
     "targets": [
      {
       "expr": "irate(syscall_latency{job=\"$host\",op=\"query\"}[$__rate_interval])",
       "legendFormat": "p{{percentile}}"
      }
     ]
    },
    {
     "title": "IPC Rate",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 245 },
     "targets": [
      {
       "expr": "sum(irate(syscall{job=~\"$host\",op=\"ipc\"}[$__rate_interval]))",
       "legendFormat": "syscall/s"
      }
     ]
    },
    {
     "title": "IPC Latency",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 245 },
     "fieldConfig": { "defaults": { "unit": "ns" } },
     "targets": [
      {
       "expr": "irate(syscall_latency{job=\"$host\",op=\"ipc\"}[$__rate_interval])",
       "legendFormat": "p{{percentile}}"
      }
     ]
    },
    {
     "title": "Timer Rate",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 253 },
     "targets": [
      {
       "expr": "sum(irate(syscall{job=~\"$host\",op=\"timer\"}[$__rate_interval]))",
       "legendFormat": "syscall/s"
      }
     ]
    },
    {
     "title": "Timer Latency",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 253 },
     "fieldConfig": { "defaults": { "unit": "ns" } },
     "targets": [
      {
       "expr": "irate(syscall_latency{job=\"$host\",op=\"timer\"}[$__rate_interval])",
       "legendFormat": "p{{percentile}}"
      }
     ]
    },
    {
     "title": "Event Rate",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 261 },
     "targets": [
      {
       "expr": "sum(irate(syscall{job=~\"$host\",op=\"event\"}[$__rate_interval]))",
       "legendFormat": "syscall/s"
      }
     ]
    },
    {
     "title": "Event Latency",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 261 },
     "fieldConfig": { "defaults": { "unit": "ns" } },
     "targets": [
      {
       "expr": "irate(syscall_latency{job=\"$host\",op=\"event\"}[$__rate_interval])",
       "legendFormat": "p{{percentile}}"
      }
     ]
    },
    {
     "title": "Other Rate",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 269 },
     "targets": [
      {
       "expr": "sum(irate(syscall{job=~\"$host\",op=\"other\"}[$__rate_interval]))",
       "legendFormat": "syscall/s"
      }
     ]
    },
    {
     "title": "Other Latency",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 269 },
     "fieldConfig": { "defaults": { "unit": "ns" } },
     "targets": [
      {
       "expr": "irate(syscall_latency{job=\"$host\",op=\"other\"}[$__rate_interval])",
       "legendFormat": "p{{percentile}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Softirq",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 45 },
   "collapsed": true,
   "panels": [
    {
     "title": "Rate - Total",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 86 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(irate(softirq{job=~\"$host\"}[$__rate_interval]))",
       "legendFormat": "{{job}}"
      }
     ]
    },
    {
     "title": "Rate - Total",
     "type": "heatmap",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 86 },
     "targets": [
      {
       "expr": "sum by(id) (irate(softirq{job=~\"$host\"}[$__rate_interval]))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "CPU % - Total",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 118 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "expr": "sum by(job) (irate(softirq_time{job=~\"$host\"}[$__rate_interval])) / on(job) cpu_cores / 1e9",
       "legendFormat": "{{job}}"
      }
     ]
    },
    {
     "title": "CPU % - Total",
     "type": "heatmap",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 118 },
     "targets": [
      {
       "expr": "sum by(id) (irate(softirq_time{job=~\"$host\"}[$__rate_interval])) / 1e9",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  },
  {
   "title": "Block IO",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 46 },
   "collapsed": true,
   "panels": [
    {
     "title": "Throughput",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 87 },
     "fieldConfig": { "defaults": { "unit": "binBps" } },
     "targets": [
      {
       "expr": "sum by(job) (irate(blockio_bytes{job=~\"$host\"}[$__rate_interval]))",
       "legendFormat": "{{job}}"
      }
     ]
    },
    {
     "title": "Read IOPS",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 87 },
     "fieldConfig": { "defaults": { "unit": "iops" } },
     "targets": [
      {
       "expr": "sum by(job) (irate(blockio_operations{job=~\"$host\"}[$__rate_interval]))",
       "legendFormat": "{{job}}"
      }
     ]
    },
    {
     "title": "Read Throughput",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 95 },
     "fieldConfig": { "defaults": { "unit": "binBps" } },
     "targets": [
      {
       "expr": "irate(blockio_bytes{job=~\"$host\",op=\"read\"}[$__rate_interval])",
       "legendFormat": "{{job}}"
      }
     ]
    },
    {
     "title": "Read IOPS",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 95 },
     "fieldConfig": { "defaults": { "unit": "iops" } },
     "targets": [
      {
       "expr": "irate(blockio_operations{job=~\"$host\",op=\"read\"}[$__rate_interval])",
       "legendFormat": "{{job}}"
      }
     ]
    },
    {
     "title": "Write Throughput",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 103 },
     "fieldConfig": { "defaults": { "unit": "binBps" } },
     "targets": [
      {
       "expr": "irate(blockio_bytes{job=~\"$host\",op=\"write\"}[$__rate_interval])",
       "legendFormat": "{{job}}"
      }
     ]
    },
    {
     "title": "Write IOPS",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 103 },
     "fieldConfig": { "defaults": { "unit": "iops" } },
     "targets": [
      {
       "expr": "irate(blockio_operations{job=~\"$host\",op=\"write\"}[$__rate_interval])",
       "legendFormat": "{{job}}"
      }
     ]
    },
    {
     "title": "Latency - Read",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 111 },
     "fieldConfig": { "defaults": { "unit": "ns" } },
     "targets": [
      {
       "expr": "blockio_latency{job=~\"$host\",op=\"read\"}",
       "legendFormat": "p{{percentile}}"
      }
     ]
    },
    {
     "title": "Latency - Write",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 111 },
     "fieldConfig": { "defaults": { "unit": "ns" } },
     "targets": [
      {
       "expr": "blockio_latency{job=~\"$host\",op=\"write\"}",
       "legendFormat": "p{{percentile}}"
      }
     ]
    },
    {
     "title": "Size - Read",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 119 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "blockio_size{job=~\"$host\",op=\"read\"}",
       "legendFormat": "p{{percentile}}"
      }
     ]
    },
    {
     "title": "Size - Write",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 119 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "blockio_size{job=~\"$host\",op=\"write\"}",
       "legendFormat": "p{{percentile}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Rezolus",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 47 },
   "collapsed": true,
   "panels": [
    {
     "title": "CPU %",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 128 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "expr": "sum(irate(rezolus_cpu_usage{job=~\"$host\"}[$__rate_interval])) / 1e9",
       "legendFormat": "{{job}}"
      }
     ]
    },
    {
     "title": "Memory",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 128 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "rezolus_memory_usage_resident_set_size{job=\"$host\"}",
       "legendFormat": "{{job}}"
      }
     ]
    }
   ]
  }
 ]
}