// The cross-language pin for the display-binary layout.
//
// Every other test of this format tests one side against a hand-written mirror
// of the other: the Rust encoder test re-implements a decoder, the JS decoder
// test re-implements an encoder. Both can drift the same way and stay green,
// and neither would notice. This one asserts against bytes produced by the REAL
// encoder, checked in at tests/fixtures/display_wire_mixed.json together with
// the decode they should produce.
//
// The fixture is generated by:
//   UPDATE_FIXTURES=1 cargo test -p dashboard the_shared_fixture
// so a deliberate layout change regenerates it and the diff is the review
// artifact. If this test fails and you did not change the wire, a decoder is
// about to start reading the wrong columns.
import test from 'node:test';
import assert from 'node:assert/strict';
import { readFileSync } from 'node:fs';
import { decodeDisplayBinary, displayInterpolated, displayIntervals }
    from '../src/viewer/assets/lib/data.js';

const fixture = JSON.parse(
    readFileSync(new URL('./fixtures/display_wire_mixed.json', import.meta.url)),
);

const bytes = Uint8Array.from(
    fixture.hex.match(/../g).map((h) => parseInt(h, 16)),
);
const decoded = decodeDisplayBinary(bytes.buffer);

// The fixture writes NaN as null (JSON has no NaN); a non-finite edge means
// "no band at this point", the same thing the raw f64 means.
const norm = (v) => (Number.isFinite(v) ? v : null);

test('the decoder agrees with the encoder on every flag combination', () => {
    assert.equal(decoded.budget, fixture.budget);
    assert.equal(decoded.series.length, fixture.expected.length);

    for (const [i, want] of fixture.expected.entries()) {
        const got = decoded.series[i];
        const where = `series ${i} (${want.name})`;
        assert.equal(got.metric.__name__, want.name, where);
        assert.equal(got.n, want.n, `${where} point count`);
        assert.equal(got.unc, want.unc, `${where} unc flag`);
        assert.equal(got.interp, want.interp, `${where} interp flag`);

        for (const col of ['t', 'min', 'lo', 'median', 'hi', 'max']) {
            assert.deepEqual(
                Array.from(got[col]).map(norm), want[col], `${where} ${col}`,
            );
        }
        // Optional groups: present exactly when flagged, absent otherwise —
        // reading a column a series never wrote is the failure mode that
        // corrupts every LATER series rather than this one.
        if (want.unc) {
            assert.deepEqual(Array.from(got.uncLo).map(norm), want.uncLo, `${where} uncLo`);
            assert.deepEqual(Array.from(got.uncHi).map(norm), want.uncHi, `${where} uncHi`);
        } else {
            assert.equal(got.uncLo, undefined, `${where} must expose no uncLo`);
        }
        if (want.interp) {
            assert.deepEqual(
                Array.from(got.interpCol).map(norm), want.interpCol, `${where} interpCol`,
            );
        } else {
            assert.equal(got.interpCol, undefined, `${where} must expose no interpCol`);
        }
    }
});

test('the last series decodes correctly, which it only can if all the earlier ones were sized right', () => {
    // "neither" carries no optional columns, so it is the series most likely to
    // read into someone else's bytes if any preceding series was mis-sized.
    const last = decoded.series[decoded.series.length - 1];
    const want = fixture.expected[fixture.expected.length - 1];
    assert.equal(last.metric.__name__, 'neither');
    assert.deepEqual(Array.from(last.t), want.t);
    assert.deepEqual(Array.from(last.median), want.median);
});

test('the consumer helpers read the fixture the way the renderer will', () => {
    // Not just the raw columns: the two functions the chart actually calls.
    const both = decoded.series[0];
    assert.deepEqual(displayInterpolated(both), [false, true, true, false]);
    // A partial band within one series: present on the measured points, absent
    // exactly where the points are interpolated.
    const iv = displayIntervals(both);
    assert.equal(iv.length, 4);
    assert.deepEqual(iv[0], [90, 110]);
    assert.equal(iv[1], null);
    assert.equal(iv[2], null);
    assert.deepEqual(iv[3], [390, 410]);

    // A series that flagged neither exposes neither.
    assert.equal(displayInterpolated(decoded.series[3]), null);
    assert.equal(displayIntervals(decoded.series[3]), null);
});
