apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: rezolus
  labels:
    app: rezolus
    environment: base
spec:
  selector:
    matchLabels:
      app: rezolus
  template:
    metadata:
      labels:
        app: rezolus
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "4242"
        prometheus.io/path: "/metrics"
    spec:
      hostNetwork: true
      hostPID: true
      containers:
        - name: rezolus-agent
          image: samof76/rezolus
          args:
            - /config/agent.toml
          securityContext:
            privileged: true
            capabilities:
              add:
                - SYS_ADMIN
                - SYS_PTRACE
                - NET_ADMIN
                - SYS_RESOURCE
                - IPC_LOCK
                - NET_RAW
          volumeMounts:
            - name: proc
              mountPath: /host/proc
              readOnly: true
            - name: sys
              mountPath: /host/sys
              readOnly: true
            - name: dev
              mountPath: /host/dev
              readOnly: true
            - name: debugfs
              mountPath: /sys/kernel/debug
            - name: tracefs
              mountPath: /sys/kernel/debug/tracing
            - name: bpffs
              mountPath: /sys/fs/bpf
            - name: boot
              mountPath: /host/boot
              readOnly: true
            - name: modules
              mountPath: /host/lib/modules
              readOnly: true
            - name: agent-config
              mountPath: /config
          env:
            - name: NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
            - name: HOST_PROC
              value: "/host/proc"
            - name: HOST_SYS
              value: "/host/sys"
            - name: HOST_DEV
              value: "/host/dev"
          resources:
            requests:
              memory: "128Mi"
              cpu: "50m"
            limits:
              memory: "512Mi"
              cpu: "200m"
        - name: rezolus-exporter
          image: samof76/rezolus
          command: ["/usr/local/bin/rezolus"]
          args:
            - exporter
            - /config/exporter.toml
          ports:
            - containerPort: 4242
              name: metrics
              protocol: TCP
          volumeMounts:
            - name: exporter-config
              mountPath: /config
          env:
            - name: NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
          resources:
            requests:
              memory: "32Mi"
              cpu: "25m"
            limits:
              memory: "128Mi"
              cpu: "100m"
      volumes:
        - name: proc
          hostPath:
            path: /proc
        - name: sys
          hostPath:
            path: /sys
        - name: dev
          hostPath:
            path: /dev
        - name: debugfs
          hostPath:
            path: /sys/kernel/debug
        - name: tracefs
          hostPath:
            path: /sys/kernel/debug/tracing
        - name: bpffs
          hostPath:
            path: /sys/fs/bpf
        - name: boot
          hostPath:
            path: /boot
        - name: modules
          hostPath:
            path: /lib/modules
        - name: agent-config
          configMap:
            name: rez-agent-config
        - name: exporter-config
          configMap:
            name: rez-exporter-config
