apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: rezolus-monitor
spec:
  selector:
    matchLabels: {}
  endpoints:
    - port: metrics
      interval: 30s
      path: /metrics
