/* tslint:disable */
/* eslint-disable */
export const memory: WebAssembly.Memory;
export const __wbg_viewer_free: (a: number, b: number) => void;
export const __wbg_wasmcaptureregistry_free: (a: number, b: number) => void;
export const init: () => void;
export const viewer_file_metadata_json: (a: number) => [number, number];
export const viewer_get_section: (a: number, b: number, c: number) => [number, number];
export const viewer_get_sections: (a: number) => [number, number];
export const viewer_info: (a: number) => [number, number];
export const viewer_init_templates: (a: number, b: number, c: number) => [number, number];
export const viewer_metadata: (a: number) => [number, number];
export const viewer_new: (a: number, b: number, c: number, d: number) => [number, number, number];
export const viewer_query: (a: number, b: number, c: number, d: number) => [number, number];
export const viewer_query_range: (a: number, b: number, c: number, d: number, e: number, f: number) => [number, number];
export const viewer_selection: (a: number) => [number, number];
export const viewer_set_alias: (a: number, b: number, c: number) => void;
export const viewer_systeminfo: (a: number) => [number, number];
export const wasmcaptureregistry_attach: (a: number, b: number, c: number, d: number, e: number, f: number, g: number) => [number, number];
export const wasmcaptureregistry_detach: (a: number, b: number, c: number) => void;
export const wasmcaptureregistry_file_metadata_json: (a: number, b: number, c: number) => [number, number];
export const wasmcaptureregistry_get_section: (a: number, b: number, c: number, d: number, e: number) => [number, number];
export const wasmcaptureregistry_get_sections: (a: number, b: number, c: number) => [number, number];
export const wasmcaptureregistry_has: (a: number, b: number, c: number) => number;
export const wasmcaptureregistry_info: (a: number, b: number, c: number) => [number, number, number, number];
export const wasmcaptureregistry_init_templates: (a: number, b: number, c: number, d: number, e: number) => [number, number];
export const wasmcaptureregistry_metadata: (a: number, b: number, c: number) => [number, number, number, number];
export const wasmcaptureregistry_new: () => number;
export const wasmcaptureregistry_query: (a: number, b: number, c: number, d: number, e: number, f: number) => [number, number, number, number];
export const wasmcaptureregistry_query_range: (a: number, b: number, c: number, d: number, e: number, f: number, g: number, h: number) => [number, number, number, number];
export const wasmcaptureregistry_selection: (a: number, b: number, c: number) => [number, number];
export const wasmcaptureregistry_set_alias: (a: number, b: number, c: number, d: number, e: number) => [number, number];
export const wasmcaptureregistry_systeminfo: (a: number, b: number, c: number) => [number, number];
export const rust_zstd_wasm_shim_calloc: (a: number, b: number) => number;
export const rust_zstd_wasm_shim_free: (a: number) => void;
export const rust_zstd_wasm_shim_malloc: (a: number) => number;
export const rust_zstd_wasm_shim_memcmp: (a: number, b: number, c: number) => number;
export const rust_zstd_wasm_shim_memcpy: (a: number, b: number, c: number) => number;
export const rust_zstd_wasm_shim_memmove: (a: number, b: number, c: number) => number;
export const rust_zstd_wasm_shim_memset: (a: number, b: number, c: number) => number;
export const rust_zstd_wasm_shim_qsort: (a: number, b: number, c: number, d: number) => void;
export const __wbindgen_free: (a: number, b: number, c: number) => void;
export const __wbindgen_malloc: (a: number, b: number) => number;
export const __wbindgen_realloc: (a: number, b: number, c: number, d: number) => number;
export const __wbindgen_externrefs: WebAssembly.Table;
export const __externref_table_dealloc: (a: number) => void;
export const __wbindgen_start: () => void;
