[general]
# Specify the listen address for the Rezolus Exporter
listen = "0.0.0.0:4242"

# Specify the address of the Rezolus Agent
source = "127.0.0.1:4241"

[log]
# Controls the log level: "error", "warn", "info", "debug", "trace"
level = "info"

[prometheus]
# Controls whether the full distribution for each histogram is exposed via the
# prometheus endpoint (`/metrics`). This adds a considerable number of time
# series depending on the downsampling factor as each histogram bucket is
# represented as its own time series.
histograms = false

# The histogram can be downsampled for exposition to reduce the number of
# buckets, and therefore reduce the number of timeseries needed to store the
# distribution.
#
# The grouping power must be in the range 0..=3. The native histograms are
# recorded with a grouping power of 3. Any reduction in the grouping power will
# increase the relative error, as the buckets are wider with lower grouping
# powers.
#
# See https://docs.rs/histogram/ for more information about the grouping power.
#
# Power:   	    Error:		Buckets:
# 3              12.5%      496
# 2              25.0%      252
# 1              50.0%      128
# 0             100.0%       65
histogram_grouping_power = 3

# Controls whether summary percentiles for each histogram will be exposed on the
# prometheus endpoint (`/metrics`). This adds a limited number of time series
# for each histogram and is useful for environments where collecting full
# distributions is prohibitively expensive.
summaries = true
