[package]
name = "rezolus-systeminfo"
edition = "2021"
version = { workspace = true }
license = { workspace = true }
publish = false

[dependencies]
serde = { version = "1.0.188", features = ["derive"] }
