name: cargo-build

on:
  push:
  pull_request:

env:
  CARGO_TERM_COLOR: always
  RUST_BACKTRACE: full

jobs:
  # First stage: these are quick jobs that give immediate feedback on a PR.
  check:
    name: check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup-rust
      - uses: Swatinem/rust-cache@v2
        with:
          shared-key: check-${{ matrix.os }}
      - name: Install dependencies
        shell: bash
        run: |
          sudo apt update
          sudo apt-get -y install libelf-dev
      - name: cargo check
        run: |
          rustup component add rustfmt
          cargo check --all-targets

  clippy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup-rust
      - uses: Swatinem/rust-cache@v2
      - uses: taiki-e/install-action@v2
        with:
          tool: clippy-sarif,sarif-fmt
      - name: Install dependencies
        shell: bash
        run: |
          sudo apt update
          sudo apt-get -y install libelf-dev
      - name: run clippy
        run: |
          cargo clippy --all-targets --all-features --message-format json \
            | clippy-sarif \
            | tee clippy.sarif \
            | sarif-fmt
        shell: bash
        continue-on-error: true
      - uses: actions/upload-artifact@v4
        with:
          name: clippy-sarif
          path: clippy.sarif

  clippy-upload:
    runs-on: ubuntu-latest
    needs: [ clippy ]
    permissions:
      security-events: write
    steps:
    - uses: actions/checkout@v4
    - uses: actions/download-artifact@v4.1.7
      with:
        name: clippy-sarif
    - uses: github/codeql-action/upload-sarif@v2
      with:
        sarif_file: clippy.sarif

  audit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup-rust
      - uses: Swatinem/rust-cache@v2
        with:
          shared-key: check-ubuntu-latest
          save-if: false
      - name: install cargo-audit
        run: cargo install cargo-audit
      - run: |
          cargo audit

  rustfmt:
    name: rustfmt
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
      - name: cargo fmt
        shell: bash
        run: |
          rustup component add rustfmt
          cargo fmt --all -- --check

  # Second group of checks: These are more expensive than the first set so we
  # gate them on the check action succeeding.
  build:
    name: build-${{ matrix.os }}-${{ matrix.profile }}-${{ matrix.features }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ ubuntu-24.04, ubuntu-22.04, macos-latest ]
        profile: [ release, debug ]
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup-rust
      - uses: Swatinem/rust-cache@v2
        with:
          shared-key: build-${{ matrix.os }}-${{ matrix.profile }}-${{ matrix.features }}

      - name: Update cargo flags
        if: ${{ matrix.profile == 'release' }}
        run: echo 'FLAGS=--release' >> $GITHUB_ENV
        shell: bash
      - name: Update cargo flags
        if: ${{ matrix.profile == 'debug' }}
        run: echo 'FLAGS=' >> $GITHUB_ENV
        shell: bash

      - name: Install dependencies
        if: ${{ matrix.os != 'macos-latest' }}
        shell: bash
        run: |
          sudo apt update
          sudo apt-get -y install libelf-dev
          rustup component add rustfmt

      - name: build
        shell: bash
        run: |
          cargo build --workspace ${{ env.FEATURE_FLAGS }} --all-targets --locked ${{ env.FLAGS }}
      - name: test
        shell: bash
        run: |
          cargo test --workspace ${{ env.FEATURE_FLAGS }} --tests --bins --locked ${{ env.FLAGS }}
      - name: doctests
        if: ${{ matrix.profile == 'debug' }}
        shell: bash
        run: |
          cargo test --workspace ${{ env.FEATURE_FLAGS }} --locked -- --test-threads 16
      - name: smoketest
        if: ${{ matrix.profile == 'release' }}
        shell: bash
        run: |
          cargo build ${{ env.FEATURE_FLAGS }} --locked ${{ env.FLAGS }}
          sudo ./target/release/rezolus config/agent.toml & echo $! > agent.pid
          sleep 15
          ./target/release/rezolus record --duration 30s http://127.0.0.1:4241 rezolus.parquet
      - name: smoketest
        if: ${{ matrix.profile == 'debug' }}
        shell: bash
        run: |
          cargo build ${{ env.FEATURE_FLAGS }} --locked ${{ env.FLAGS }}
          sudo ./target/debug/rezolus config/agent.toml & echo $! > agent.pid
          sleep 15
          ./target/debug/rezolus record --duration 30s http://127.0.0.1:4241 rezolus.parquet

  check-success:
    name: verify all tests pass
    runs-on: ubuntu-latest
    needs:
      - build
      - check
      - rustfmt
      - clippy
      - clippy-upload

    steps:
      - name: no-op
        run: |
          echo "All checks passed!"
